# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('short_bio', models.CharField(max_length=255)),
                ('job_status', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=50)),
                ('looking_for_job', models.BooleanField(default=True)),
                ('github_profile', models.URLField(blank=True, default='', max_length=75, null=True)),
                ('facebook_profile', models.URLField(blank=True, default='', max_length=75, null=True)),
                ('twitter_profile', models.URLField(blank=True, default='', max_length=75, null=True)),
                ('linkedin_profile', models.URLField(blank=True, default='', max_length=75, null=True)),
                ('codepen_profile', models.URLField(blank=True, default='', max_length=75, null=True)),
                ('discord_profile', models.CharField(default='', max_length=25)),
                ('familiar_technologies', models.CharField(blank=True, default='', max_length=255)),
                ('interested_technologies', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
