# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codepen_profile',
            field=models.URLField(blank=True, default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discord_profile',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='familiar_technologies',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_profile',
            field=models.URLField(blank=True, default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interested_technologies',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_status',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for_job',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='short_bio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.URLField(blank=True, default=None, max_length=75, null=True),
        ),
    ]
