# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='books',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
