# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_auto_20171020_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='CurriculumBookChapterShip',
            new_name='BookChapterRelationShip',
        ),
        migrations.RenameModel(
            old_name='CurriculumChapterPageShip',
            new_name='ChapterPageRelationShip',
        ),
        migrations.RenameModel(
            old_name='CurriculumPage',
            new_name='Page',
        ),
        migrations.RemoveField(
            model_name='curriculumbook',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='curriculumbook',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='curriculumbook',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='curriculumchapter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='curriculumchapter',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='curriculumchapter',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='bookchapterrelationship',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='bookchapterrelationship',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Chapter'),
        ),
        migrations.AlterField(
            model_name='chapterpagerelationship',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Chapter'),
        ),
        migrations.DeleteModel(
            name='CurriculumBook',
        ),
        migrations.DeleteModel(
            name='CurriculumChapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.ManyToManyField(through='books.ChapterPageRelationShip', to='books.Page'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_chapter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(through='books.BookChapterRelationShip', to='books.Chapter'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
