# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20171020_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapterrelationship',
            name='position',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='chapterpagerelationship',
            name='position',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
