# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20171020_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='pages',
        ),
    ]
